
pub const TEXT_DATA: [&str; 6] = [ 
  "Who am I?\n--------------------------------\nHi, I am sabbir. I am a Full Stack Web Developer. I am very hardworking and dedicated to my work. For example, sometimes I get sick only on the weekends.\nI can speak 2 languages (bengali and english), but can write and understand another five languages (JavaScript, Rust, Python, PHP, C).\nI am very god following person. I used to follow most of the gods on twitter.\n",

  "Where I live?\n--------------------------------\nI am from Bangladesh, living in UAE.\n Do you know where Bangladesh is? Well, you will receive a free map of Bangladesh if you ever buy a map of India.\nDo not think we are cheap. We are quite brave. Bangladesh is one of two nations after the USA in the world who gained its independence by winning the liberation war.\nSome information about my country is given here. Bangladesh is a densely populated excessively green country.\n We have 12 Gregorian calendar months (as you have known), 2 bengali months which are \"Falgun\" and \"Baishakh\", 2 arabic months which are \"Ramadan\" and \"Dhu\'l-Hijjah\".\n We have 3 sessions which are hot, rainy and not so hot session.",

" My Story\n I wanted to be HERCULES, but I'm not that strong\n Wanted to be ALEXANDER-THE-GREAT, but I was not the one chosen\n Wanted to be DIOGENES, but I am not that good\n  Wanted to be HEROSTRATUS, but thankfully, I am not that bad\n Wanted to be LEONARDO DA VINCI, wanted to build MONALISA. I truly wish I could\n Wanted to be NIKOLA TESLA, but that brilliance is beyond my limits\n Wanted to be Ashutosh,  but I am simply not that lucky\n So what am I?\n
 I am DON QUIXOTE of LA MANCHA.\n What will I be?\n I will be Lao Tzu",

  "My Aim in LIFE\n--------------------------------\n One day, Lord Krishna was returning to his kingdom. All the villagers were meticulously decorating their homes and roads, so that their God's Ratha Yatra (chariot procession) would look more resplendent.\nBut some villagers intentionally kept their homes and roads completely in darkness.\nNaturally, Krishna asked them why they had chosen to do that.\nThey replied, \"Dear God, your Ratha Yatra is already so bright. We realized that if we remained in darkness, your glorious procession would shine much more brilliantly.\"\nI wish I could be like those villagers.",

  "My Nightmare\n--------------------------------\n  As a software engineer, the thing I'm most afraid of is the dreaded \"500: Internal Server Error.\"\n But my absolute worst nightmare is when someone finds out what I do and asks me: \"So you are a software engineer, can you fix my smartphone or computer?\" I\'m still working on how to reply to that one, though.\"\n My Day-dream\n--------------------------------\n One day, I will arrive at the office on time, write code all day without a single test, successfully deploy it directly to production without a bug, and head back home on time for a sound sleep.\n And yes, I know this is never going to happen.\n",

  "Hobbies\n--------------------------------\nI love reading books and have a deep interest in mythology and history.\n My favorite writers are Maupassant and Mirza Ghalib.\n My favorite book is Don Quixote by Miguel de Cervantes. The book I've read the most but never finished is the English-to-Bengali Dictionary. And the books that truly make me cry are my checkbooks—and that might be because of my own cache issues\n \n Social Life\n--------------------------------\n I don't post on social media regularly. but regularly, I try to do a git commit."
 ];
